- hosts: all
  roles:
    - orchestrate-devstack
    # Run bindep and test-setup after devstack so that they won't interfere
    - role: bindep
      bindep_profile: test
      bindep_dir: "{{ zuul_work_dir }}"
    - test-setup
    - ensure-tox
    - additional-tempauth-users
    - additional-keystone-users
    - dsvm-additional-middlewares
